kernel: Add missing $(OBJS) dependency to target
Some targets such as atarist need objects expected to be made by
Kernel/Makefile.

This fixes problems where target makefiles got confused and attempted to
compile these objects themselves:

cc    -c -o ../start.o ../start.c
../start.c:1:10: fatal error: kernel.h: No such file or directory
    1 | #include <kernel.h>
      |          ^~~~~~~~~~
compilation terminated.