dk-tm4c129x: fix linker error
LOBJ are listed in OBJS, so there is no need to list armrelocate.o
separately as it results in linker error:

```
Kernel/platform-dk-tm4c129x/../lib/armrelocate.c:10: multiple definition of `plt_relocate'; armrelocate.o:Kernel/platform-dk-tm4c129x/../lib/armrelocate.c:10: first defined here
```

Signed-off-by: Paul Osmialowski <pawel.osmialowski@arm.com>